### ISSUE TITLE
[Feature] Make `cli-table` formatting optional

### ISSUE THREAD

**Issue by stephenyeargin** [maxbeatty/hubot-uber#3]
### Use Case

I have this connected to both IRC and Slack adapters. When I run it in an IRC client with a non-fixed-width font, I get some rather janky output

![screen shot 2015-12-17 at 12 27 50 pm](https://cloud.githubusercontent.com/assets/80459/11878158/9f3d2efa-a4b9-11e5-8d38-e04cbd556ec8.png)

### Solution

So, I would propose either:

- Ditching this format entirely (not really feeling that option)
- Making it an environment variable configuration option, e.g. `HUBOT_UBER_FORMAT_TABLES=0`

**Comment by maxbeatty** [comment]
I'm assuming Zach was using Campfire [here](https://gist.github.com/holman/55130df8c9ba9fbce085#file-example-png) since I thought that's what GitHub was using for a long time. I'm not sure cli-table is pretty in HipChat, IRC, or Slack. A better formatting solution that's decent across providers would be ideal. I'm open to other ideas and PRs :rocket:
